<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tracked_robot">

  <!-- Robot dimensions properties -->
  <xacro:property name="chassis_width" value="0.78" />   <!-- 780mm -->
  <xacro:property name="chassis_length" value="1.015" /> <!-- 1015mm -->
  <xacro:property name="chassis_height" value="0.72" />  <!-- 720mm -->
  <xacro:property name="ground_clearance" value="0.05" /> <!-- 5cm ground clearance -->

  <!-- Material colors -->
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>
  
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <material name="green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>

  <!-- Base link (robot center) -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
    </inertial>
  </link>

  <!-- Robot Footprint -->
  <link name="base_footprint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.0001" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
    </inertial>
  </link>

  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 ${ground_clearance}" rpy="0 0 0" />
  </joint>
  
  <!-- Main chassis body -->
  <link name="chassis_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="60.0"/>
      <inertia 
        ixx="${60.0*(chassis_width*chassis_width+chassis_height*chassis_height)/12}" 
        ixy="0" 
        ixz="0"
        iyy="${60.0*(chassis_length*chassis_length+chassis_height*chassis_height)/12}" 
        iyz="0"
        izz="${60.0*(chassis_length*chassis_length+chassis_width*chassis_width)/12}" />
    </inertial>
  </link>

  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Jetson Orin NX -->
  <link name="jetson_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.12 0.18 0.03" />
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.12 0.18 0.03" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>

  <joint name="jetson_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="jetson_link" />
    <origin xyz="0 0 ${chassis_height/2 - 0.05}" rpy="0 0 0" />
  </joint>

</robot>
