<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tracked_robot">

  <!-- Include common properties -->
  <xacro:include filename="$(find minimal_tracked_robot)/urdf/tracked_robot_properties.xacro" />
  
  <!-- Include the ZED camera macro -->
  <xacro:include filename="$(find minimal_tracked_robot)/urdf/zed_camera.xacro" />
  
  <!-- Include the tracked chassis macro -->
  <xacro:include filename="$(find minimal_tracked_robot)/urdf/tracked_chassis.xacro" />
  
  <!-- Include transmissions for motion -->
  <xacro:include filename="$(find minimal_tracked_robot)/urdf/tracked_robot_transmissions.xacro" />
  
  <!-- Include gazebo plugins -->
  <xacro:include filename="$(find minimal_tracked_robot)/urdf/tracked_robot_gazebo.xacro" />

  <!-- Base link (robot center) -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
      <material name="transparent">
        <color rgba="0 0 0 0" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
    </inertial>
  </link>

  <!-- Robot Footprint -->
  <link name="base_footprint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
      <material name="transparent" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.0001" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
    </inertial>
  </link>

  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 ${ground_clearance}" rpy="0 0 0" />
  </joint>
  
  <!-- Include the robot chassis -->
  <xacro:tracked_chassis parent="base_link" />
  
  <!-- Include the ZED2i camera -->
  <xacro:zed_camera name="zed2i" parent="chassis_link">
    <origin xyz="${chassis_length/2 - 0.05} 0 ${chassis_height/2 + 0.05}" rpy="0 0 0" />
  </xacro:zed_camera>
  
  <!-- IMU link -->
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 0.02" />
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 0.02" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="imu_link" />
    <origin xyz="0 0 ${chassis_height/2 - 0.02}" rpy="0 0 0" />
  </joint>
    
  <!-- Auto-docking IR sensor -->
  <link name="dock_ir_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.02 0.04 0.02" />
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.02 0.04 0.02" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
    </inertial>
  </link>

  <joint name="dock_ir_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="dock_ir_link" />
    <origin xyz="${-chassis_length/2 + 0.02} 0 ${-chassis_height/2 + 0.02}" rpy="0 0 0" />
  </joint>

  <!-- Jetson Orin NX -->
  <link name="jetson_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.12 0.18 0.03" />
      </geometry>
      <material name="green">
        <color rgba="0 0.8 0 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.12 0.18 0.03" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>

  <joint name="jetson_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="jetson_link" />
    <origin xyz="0 0 ${chassis_height/2 - 0.05}" rpy="0 0 0" />
  </joint>

</robot>
